"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: inspire
  IDL file: inspire_hand_touch.idl

"""

from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

@dataclass
@annotate.final
@annotate.autoid("sequential")
class inspire_hand_touch(idl.IdlStruct, typename="inspire.inspire_hand_touch"):
    little_tip_3: types.sequence[types.int16, 9]
    little_top_2: types.sequence[types.int16, 96]
    little_palm_1: types.sequence[types.int16, 80]

    ring_tip_3: types.sequence[types.int16, 9]
    ring_top_2: types.sequence[types.int16, 96]
    ring_palm_1: types.sequence[types.int16, 80]

    middle_tip_3: types.sequence[types.int16, 9]
    middle_top_2: types.sequence[types.int16, 96]
    middle_palm_1: types.sequence[types.int16, 80]

    index_tip_3: types.sequence[types.int16, 9]
    index_top_2: types.sequence[types.int16, 96]
    index_palm_1: types.sequence[types.int16, 80]

    thumb_tip_4: types.sequence[types.int16, 9]
    thumb_top_3: types.sequence[types.int16, 96]
    thumb_middle_2: types.sequence[types.int16, 9]
    thumb_palm_1: types.sequence[types.int16, 96]

    palm: types.sequence[types.int16, 112]


